### ISSUE TITLE
Create multiple databases

### ISSUE THREAD

**Issue by nitintutlani** [openshift/mysql#125]
When using root access I am not able to create multiple databases inside a single container. I get grant privileges error.

```
mysql> CREATE DATABASE demoDB;
Query OK, 1 row affected (0.00 sec)
mysql> GRANT ALL PRIVILEGES ON demoDB.* TO 'demo'@'%' IDENTIFIED BY 'demo';
ERROR 1044 (42000): Access denied for user 'root'@'%' to database 'demoDB'
```

To resolve this I have to:
```
mysql> UPDATE mysql.user SET Grant_priv='Y', Super_priv='Y' WHERE User='root';
mysql> FLUSH PRIVILEGES;
mysql> GRANT ALL ON *.* TO 'root'@'localhost';
Query OK, 0 rows affected (0.00 sec)
mysql> GRANT ALL PRIVILEGES ON demoDB.* TO 'demo'@'%' IDENTIFIED BY 'demo';
Query OK, 0 rows affected (0.00 sec)
```
By default, root user does not have grant and super privileges.

Any help is appreciated. I need to make sure the mysql 5.6 images works out of the box for me otherwise I will have to rebuild a new image.

**Comment by mfojtik** [comment]
@hhorak something you guys are interested fixing?

**Comment by mnagy** [comment]
@nitintutlani root should have super privileges. When I start the container with `docker run -ti -e MYSQL_ROOT_PASSWORD=pass --rm openshift/mysql-56-centos7` and then execute mysql from inside of the container, I can see this:
```
mysql> select user,host,Grant_priv,Super_priv from mysql.user where user='root';
+------+--------------+------------+------------+
| user | host         | Grant_priv | Super_priv |
+------+--------------+------------+------------+
| root | localhost    | Y          | Y          |
| root | 3945ff9feb04 | Y          | Y          |
| root | 127.0.0.1    | Y          | Y          |
| root | ::1          | Y          | Y          |
| root | %            | N          | Y          |
+------+--------------+------------+------------+
```
So that means that the Grant privilege is only enabled if you are connecting from localhost. Can you verify that creating a new database and then granting the access rights to the user will work when executed from the inside of the container?

We could grant the granting privilege to root no matter where he connects from.

**Comment by nitintutlani** [comment]
Sorry and yes, the error I received is related grant_priv only. Looking at the above I am hopeful, this should work and can be also be fixed from inside container shell.

However, if you consider this to be part of database container assembly, I would request you to update this image. So we can get a true root access without any post assemble tweaks.
